-- DropForeignKey
ALTER TABLE `aikon_articulo` DROP FOREIGN KEY `AIKON_ARTICULO_FA_CODIGO_fkey`;

-- AlterTable
ALTER TABLE `aikon_articulo` MODIFY `FA_CODIGO` VARCHAR(20) NULL;

-- CreateTable
CREATE TABLE `AIKON_MARCA` (
    `MA_CODIGO` VARCHAR(3) NOT NULL,
    `MA_DESCRI` VARCHAR(30) NULL,
    `MA_FECHAMODIF` DATETIME(3) NULL,

    PRIMARY KEY (`MA_CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `AIKON_ARTICULO` ADD CONSTRAINT `AIKON_ARTICULO_FA_CODIGO_fkey` FOREIGN KEY (`FA_CODIGO`) REFERENCES `AIKON_FAMILIA`(`FA_CODIGO`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `AIKON_ARTICULO` ADD CONSTRAINT `AIKON_ARTICULO_MA_CODIGO_fkey` FOREIGN KEY (`MA_CODIGO`) REFERENCES `AIKON_MARCA`(`MA_CODIGO`) ON DELETE SET NULL ON UPDATE CASCADE;
