export const ejemploArray = [
    {
        "ar_codigo": "00020025",
        "ar_descri": "AIRE COMPACTO FEDDERS TAC 49 CWA/RIF 4900W 4200F/SOLO",
        "um_codigo": "UN",
        "um_codcom": "UN",
        "ar_barras": "00020025",
        "AR_IVAPORCEN": 21.0,
        "ma_descri": "FEDDERS",
        "fa_nombre": "AIRE COMPACTO",
        "fa_codigo": "0002",
        "st_stock": 3.0,
        "ar_umexacta": "S",
        "ar_cosbru": 0.0,
        "ar_cosrep": 9015.11,
        "ar_cosucp": 9015.12,
        "fecha_ucp": null,
        "ar_equum": 1.0,
        "ar_bonifi": "0",
        "ar_desmax": "5,5",
        "ar_minimavta": 0.0,
        "ar_cosnet": 570000.0,
        "um_codigo_descri": "UNIDAD",
        "um_codcom_descri": "UNIDAD",
        "un_fijarprecio": "",
        "un_pisadesc": "",
        "AR_ESUNILEVER": "",
        "AR_UNICAJ": 1.0,
        "AR_ESUNILEVER_ACTIVO": "",
        "ar_memo": "aire acondicionado - Ventana - frio solo - 4900 FRIGORIAS - POTENCIA 4200 WATS - DESHUMIDIFICACION - FUNCION SUEÑO\r\nTIMER - FUNCIONAMIENTO SILENCIOSO - FILTRO lavable - EFICIENCIA ENERGETICA A - TIPO DE GAS R410A\r\nCOLOR blanco - ORIGEN ARGENTINA\r\nCapacidad (en frigorias): 4224 - Potencia Electrica (en watts)Potencia Electrica (en watts): 4900\r\n- Alto (en cm): 43\r\n- Ancho (en cm): 66\r\n- Profundidad (en cm): 68\r\n- Observaciones: tuberia de cobre - reinicio automatico\r\n- Codigo de Articulo: 001020113000",
        "ar_descria": "AIRE COMPACTO FEDDERS TAC 49 CWA/RIF 4900WATS 4200 FRIGORIAS FIO SOLO",
        "ar_tamano": "Grande",
        "ar_alto": 0.0,
        "ar_ancho": 0.0,
        "ar_profundo": 0.0,
        "ar_color": "",
        "ar_peso": 0.0,
        "ar_litros": 0.0,
        "AR_ES_COMBO": "N",
        "AR_ESDECOMPRAS": "S",
        "AR_ESDEVENTAS": "S",
        "MO_CODIGO": "",
        "AR_FECHAALTA": "\/Date(1720407600000-0300)\/",
        "RE1_CODIGO": "00001",
        "RE2_CODIGO": "00001",
        "ESA_CODIGO": "01",
        "MA_CODIGO": "484",
        "AR_FECHAMODIF": "\/Date(1702668720000-0300)\/",
        "AR_MESESGARANTIA": 0.0
    },
    {
        "ar_codigo": "00030007",
        "ar_descri": "AIRE PORT RCA AAPR12XP 2666FG 3100W F/C PANEL TACTIL ",
        "um_codigo": "UN",
        "um_codcom": "UN",
        "ar_barras": "00030007",
        "AR_IVAPORCEN": 21.0,
        "ma_descri": "RCA",
        "fa_nombre": "AIRE PORTATIL",
        "fa_codigo": "0003",
        "st_stock": 9.0,
        "ar_umexacta": "S",
        "ar_cosbru": 0.0,
        "ar_cosrep": 7377.4,
        "ar_cosucp": 193830.27,
        "fecha_ucp": "03/11/2023",
        "ar_equum": 1.0,
        "ar_bonifi": "0",
        "ar_desmax": "5,5",
        "ar_minimavta": 0.0,
        "ar_cosnet": 388500.0,
        "um_codigo_descri": "UNIDAD",
        "um_codcom_descri": "UNIDAD",
        "un_fijarprecio": "",
        "un_pisadesc": "",
        "AR_ESUNILEVER": "N",
        "AR_UNICAJ": 1.0,
        "AR_ESUNILEVER_ACTIVO": "N",
        "ar_memo": "Capacidad de refrigeración de 3100W.\r\nCapacidad de calefacción de 2850 W.\r\nFrigorías: 2666.\r\nCon función deshumidificación.\r\nEficiencia energética: A.\r\nCuenta con función de dormir.\r\nIncluye control remoto.\r\nDimensiones: 44cm de ancho x 68cm de alto x 32cm de profundidad.\r\nTiene temporizador.",
        "ar_descria": "AIRE PORT RCA AAPR12XP 3100W F/C PANEL TACTIL ",
        "ar_tamano": "Grande",
        "ar_alto": 0.0,
        "ar_ancho": 0.0,
        "ar_profundo": 0.0,
        "ar_color": "",
        "ar_peso": 0.0,
        "ar_litros": 0.0,
        "AR_ES_COMBO": "N",
        "AR_ESDECOMPRAS": "S",
        "AR_ESDEVENTAS": "S",
        "MO_CODIGO": "",
        "AR_FECHAALTA": "\/Date(1720407600000-0300)\/",
        "RE1_CODIGO": "00001",
        "RE2_CODIGO": "00001",
        "ESA_CODIGO": "01",
        "MA_CODIGO": "360",
        "AR_FECHAMODIF": "\/Date(1702668600000-0300)\/",
        "AR_MESESGARANTIA": 0.0
    },
    {
        "ar_codigo": "00040031",
        "ar_descri": "A SPLIT SURREY WAIRA 553 AEQ 1801 F 4500 F/C",
        "um_codigo": "UN",
        "um_codcom": "UN",
        "ar_barras": "00040031",
        "AR_IVAPORCEN": 21.0,
        "ma_descri": "SURREY",
        "fa_nombre": "AIRE SPLIT",
        "fa_codigo": "0004",
        "st_stock": 4.0,
        "ar_umexacta": "S",
        "ar_cosbru": 0.0,
        "ar_cosrep": 0.0,
        "ar_cosucp": 0.0,
        "fecha_ucp": null,
        "ar_equum": 1.0,
        "ar_bonifi": "0",
        "ar_desmax": "5,5",
        "ar_minimavta": 0.0,
        "ar_cosnet": 570000.0,
        "um_codigo_descri": "UNIDAD",
        "um_codcom_descri": "UNIDAD",
        "un_fijarprecio": "",
        "un_pisadesc": "",
        "AR_ESUNILEVER": "",
        "AR_UNICAJ": 1.0,
        "AR_ESUNILEVER_ACTIVO": "",
        "ar_memo": "",
        "ar_descria": "SPLIT 4500 FRIO CALOR",
        "ar_tamano": "Grande",
        "ar_alto": 0.0,
        "ar_ancho": 0.0,
        "ar_profundo": 0.0,
        "ar_color": "",
        "ar_peso": 0.0,
        "ar_litros": 0.0,
        "AR_ES_COMBO": "N",
        "AR_ESDECOMPRAS": "S",
        "AR_ESDEVENTAS": "S",
        "MO_CODIGO": "",
        "AR_FECHAALTA": "\/Date(1720407600000-0300)\/",
        "RE1_CODIGO": "00001",
        "RE2_CODIGO": "00001",
        "ESA_CODIGO": "01",
        "MA_CODIGO": "407",
        "AR_FECHAMODIF": "\/Date(1702669740000-0300)\/",
        "AR_MESESGARANTIA": 0.0
    },
    {
        "ar_codigo": "00040065",
        "ar_descri": "A SPLIT CARRIER NEXGEN 53 HSR 1801 F 4500 F/C",
        "um_codigo": "UN",
        "um_codcom": "UN",
        "ar_barras": "00040065",
        "AR_IVAPORCEN": 21.0,
        "ma_descri": "CARRIER",
        "fa_nombre": "AIRE SPLIT",
        "fa_codigo": "0004",
        "st_stock": 2.0,
        "ar_umexacta": "S",
        "ar_cosbru": 0.0,
        "ar_cosrep": 0.0,
        "ar_cosucp": 0.0,
        "fecha_ucp": null,
        "ar_equum": 1.0,
        "ar_bonifi": "0",
        "ar_desmax": "5,5",
        "ar_minimavta": 0.0,
        "ar_cosnet": 585000.0,
        "um_codigo_descri": "UNIDAD",
        "um_codcom_descri": "UNIDAD",
        "un_fijarprecio": "",
        "un_pisadesc": "",
        "AR_ESUNILEVER": "",
        "AR_UNICAJ": 1.0,
        "AR_ESUNILEVER_ACTIVO": "",
        "ar_memo": "",
        "ar_descria": "SPLIT 4500 FRIO CALOR",
        "ar_tamano": "Grande",
        "ar_alto": 0.0,
        "ar_ancho": 0.0,
        "ar_profundo": 0.0,
        "ar_color": "",
        "ar_peso": 0.0,
        "ar_litros": 0.0,
        "AR_ES_COMBO": "N",
        "AR_ESDECOMPRAS": "S",
        "AR_ESDEVENTAS": "S",
        "MO_CODIGO": "",
        "AR_FECHAALTA": "\/Date(1720407600000-0300)\/",
        "RE1_CODIGO": "00001",
        "RE2_CODIGO": "00001",
        "ESA_CODIGO": "01",
        "MA_CODIGO": "081",
        "AR_FECHAMODIF": "\/Date(1702669740000-0300)\/",
        "AR_MESESGARANTIA": 0.0
    },
    {
        "ar_codigo": "00040110",
        "ar_descri": "A SPLIT ELECTROLUX 3500 W FRIO/CALOR EXSH35WCN",
        "um_codigo": "UN",
        "um_codcom": "UN",
        "ar_barras": "00040110",
        "AR_IVAPORCEN": 21.0,
        "ma_descri": "ELECTROLUX",
        "fa_nombre": "AIRE SPLIT",
        "fa_codigo": "0004",
        "st_stock": 1.0,
        "ar_umexacta": "S",
        "ar_cosbru": 0.0,
        "ar_cosrep": 0.0,
        "ar_cosucp": 5279.62,
        "fecha_ucp": null,
        "ar_equum": 1.0,
        "ar_bonifi": "0",
        "ar_desmax": "5,5",
        "ar_minimavta": 0.0,
        "ar_cosnet": 389000.0,
        "um_codigo_descri": "UNIDAD",
        "um_codcom_descri": "UNIDAD",
        "un_fijarprecio": "",
        "un_pisadesc": "",
        "AR_ESUNILEVER": "N",
        "AR_UNICAJ": 1.0,
        "AR_ESUNILEVER_ACTIVO": "N",
        "ar_memo": "Alto (mm)\t280 - Ancho (mm) 835 - Fondo (mm) 220\r\nFunción Sueño\r\nPara un descanso agradable, esta función acondiciona el ambiente durante las horas de sueño, mediante un ajuste gradual y automático de la temperatura, evitando así las temperaturas excesivas.\r\nFunción Inteligente\r\nMediante esta opción el equipo sleccionará automáticamente el modo de funcionamiento (frío, calor o ventilación) acorde a la temperatura deseada.\r\nHot start\r\nEn modo calor, el ventilador de launidad interior comienza a funcionar sólo cuando el radiador está lo suficientemente caliente, de esta manera evita inyectar aire frío en el ambiente a calefaccionar.\r\nDeshumidificación saludable\r\nLos equipos logran un clima natural y placentero quitando la humedad excesiva del aire, sin alterar la temperatura.\r\nBajo nivel sonoro\r\nVentiladores mucho más silenciosos permiten que el aire se distribuya en forma suave y pareja por todo el ambiente.\r\nAuto-restart\r\nLuego de un corte energético, el equipo se reinicia en forma automática con los valores seteados previamente.",
        "ar_descria": "SPLIT 3500WATS FRIO CALOR EXSH35WCN",
        "ar_tamano": "Grande",
        "ar_alto": 0.0,
        "ar_ancho": 0.0,
        "ar_profundo": 0.0,
        "ar_color": "",
        "ar_peso": 0.0,
        "ar_litros": 0.0,
        "AR_ES_COMBO": "N",
        "AR_ESDECOMPRAS": "S",
        "AR_ESDEVENTAS": "S",
        "MO_CODIGO": "",
        "AR_FECHAALTA": "\/Date(1720407600000-0300)\/",
        "RE1_CODIGO": "00001",
        "RE2_CODIGO": "00001",
        "ESA_CODIGO": "01",
        "MA_CODIGO": "136",
        "AR_FECHAMODIF": "\/Date(1702669740000-0300)\/",
        "AR_MESESGARANTIA": 0.0
    },
    {
        "ar_codigo": "00040114",
        "ar_descri": "A SPLIT PHILCO PHPTH 7217N 72000 - APROX 18000 F/C TRIFASICO",
        "um_codigo": "UN",
        "um_codcom": "UN",
        "ar_barras": "00040114",
        "AR_IVAPORCEN": 21.0,
        "ma_descri": "PHILCO",
        "fa_nombre": "AIRE SPLIT",
        "fa_codigo": "0004",
        "st_stock": 2.0,
        "ar_umexacta": "S",
        "ar_cosbru": 0.0,
        "ar_cosrep": 24954.0,
        "ar_cosucp": 25043.3,
        "fecha_ucp": null,
        "ar_equum": 1.0,
        "ar_bonifi": "0",
        "ar_desmax": "5,5",
        "ar_minimavta": 0.0,
        "ar_cosnet": 2488000.0,
        "um_codigo_descri": "UNIDAD",
        "um_codcom_descri": "UNIDAD",
        "un_fijarprecio": "",
        "un_pisadesc": "",
        "AR_ESUNILEVER": "N",
        "AR_UNICAJ": 1.0,
        "AR_ESUNILEVER_ACTIVO": "N",
        "ar_memo": "• AIRE ACONDICIONADO PISO TECHO PHILCO  PHPTH7217N \r\n• Capacidad (KCAL/H) 18000. - • TRIFASICO. \r\n\r\n• Unidad Interior: \r\n• Capacidad nominal: 6 TR – 72000 BTU/h. - • Circulación de aire: 2300 m³/h.  - • Refrigerante: R410a. - • Carga refrigerante: 3,20 Kg. \r\n• Nivel de ruido máximo interior: 60 dB. - • Alimentación: 380 V / 50 Hz. \r\n• Altura 23,5 Cm - • Ancho 165,0 Cm. - • Prof: 67,5 Cm. - • Peso: 39 kg. \r\n\r\n• Unidad Exterior: \r\n• Frío / Calor Refrigerante Ecológico R410 A. - -• Auto Descongelamiento.  - • Compresor Scroll. - • Control Remoto Inalámbrico. \r\n• Condensadora Horizontal. - • Presostato Alta / Baja. \r\n• Altura 117,0 Cm - • Ancho 90,0 Cm. - • Prof: 35,0 Cm. - • Peso: 97 kg. \r\n\r\n• Origen: China. \r\n• Garantía: 12 Meses. \r\n",
        "ar_descria": "SPLIT 18000 FRIO CALOR TRIFASICO",
        "ar_tamano": "Grande",
        "ar_alto": 0.0,
        "ar_ancho": 0.0,
        "ar_profundo": 0.0,
        "ar_color": "",
        "ar_peso": 0.0,
        "ar_litros": 0.0,
        "AR_ES_COMBO": "N",
        "AR_ESDECOMPRAS": "S",
        "AR_ESDEVENTAS": "S",
        "MO_CODIGO": "",
        "AR_FECHAALTA": "\/Date(1720407600000-0300)\/",
        "RE1_CODIGO": "00001",
        "RE2_CODIGO": "00001",
        "ESA_CODIGO": "01",
        "MA_CODIGO": "335",
        "AR_FECHAMODIF": "\/Date(1709729700000-0300)\/",
        "AR_MESESGARANTIA": 0.0
    },
    {
        "ar_codigo": "00040116",
        "ar_descri": "A SPLIT SURREY VITA SMART VFQ 1801 F 5300W F/C  4550FG",
        "um_codigo": "UN",
        "um_codcom": "UN",
        "ar_barras": "00040116",
        "AR_IVAPORCEN": 21.0,
        "ma_descri": "SURREY",
        "fa_nombre": "AIRE SPLIT",
        "fa_codigo": "0004",
        "st_stock": 3.0,
        "ar_umexacta": "S",
        "ar_cosbru": 0.0,
        "ar_cosrep": 12498.77,
        "ar_cosucp": 12498.8,
        "fecha_ucp": null,
        "ar_equum": 1.0,
        "ar_bonifi": "0",
        "ar_desmax": "5,5",
        "ar_minimavta": 0.0,
        "ar_cosnet": 585000.0,
        "um_codigo_descri": "UNIDAD",
        "um_codcom_descri": "UNIDAD",
        "un_fijarprecio": "",
        "un_pisadesc": "",
        "AR_ESUNILEVER": "N",
        "AR_UNICAJ": 1.0,
        "AR_ESUNILEVER_ACTIVO": "N",
        "ar_memo": "Watts: 5300W - Frigorías: 4550 - Color: blanco - Modo: frío-calor\r\nFunciones: smart control, follow me, detección pérdida de refrigerante, sleep y reencendido automático\r\nFiltro anti-alergias/bacterias - Eficiencia energética A - Timer programable - Pantalla digital \r\nDimensiones de la unidad interior: 31 x 95 x 22,5 cm\r\nDimensiones de la unidad exterior: 55 x 82,5 x 31,5 cm\r\nPeso de la unidad interior: 12 kg\r\nPeso de la unidad exterior: 43 kg\r\nOrigen: Argentina\r\nGarantía del proveedor: 12 meses",
        "ar_descria": "SPLIT 2900 FRIGORIAS FRIO/CALOR. SMART CONTROL.",
        "ar_tamano": "Grande",
        "ar_alto": 0.0,
        "ar_ancho": 0.0,
        "ar_profundo": 0.0,
        "ar_color": "",
        "ar_peso": 0.0,
        "ar_litros": 0.0,
        "AR_ES_COMBO": "N",
        "AR_ESDECOMPRAS": "S",
        "AR_ESDEVENTAS": "S",
        "MO_CODIGO": "",
        "AR_FECHAALTA": "\/Date(1720407600000-0300)\/",
        "RE1_CODIGO": "00001",
        "RE2_CODIGO": "00001",
        "ESA_CODIGO": "01",
        "MA_CODIGO": "407",
        "AR_FECHAMODIF": "\/Date(1702669740000-0300)\/",
        "AR_MESESGARANTIA": 0.0
    }
]