-- CreateTable
CREATE TABLE `aikon_lista_precio` (
    `LP_CODIGO` VARCHAR(2) NOT NULL,
    `LP_DESCRI` VARCHAR(30) NULL,
    `LP_FECACT` DATETIME(3) NULL,
    `LP_FECVIG` DATETIME(3) NULL,
    `LP_PVCONSULTA` VARCHAR(1) NULL,
    `LP_VERCOLCONSART` VARCHAR(1) NULL,
    `LP_FECHAMODIF` DATETIME(3) NULL,

    PRIMARY KEY (`LP_CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `aikon_art_precio` (
    `AR_CODIGO` VARCHAR(24) NOT NULL,
    `LP_CODIGO` VARCHAR(2) NOT NULL,
    `AP_PRECIO` DECIMAL(15, 2) NULL,
    `AP_UTILID` DECIMAL(6, 2) NULL,
    `AP_FECMOD` DATETIME(3) NULL,

    PRIMARY KEY (`AR_CODIGO`, `LP_CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `aikon_art_precio` ADD CONSTRAINT `aikon_art_precio_AR_CODIGO_fkey` FOREIGN KEY (`AR_CODIGO`) REFERENCES `aikon_articulo`(`AR_CODIGO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `aikon_art_precio` ADD CONSTRAINT `aikon_art_precio_LP_CODIGO_fkey` FOREIGN KEY (`LP_CODIGO`) REFERENCES `aikon_lista_precio`(`LP_CODIGO`) ON DELETE RESTRICT ON UPDATE CASCADE;
